### PR TITLE
Update version number to 2.10

### PR DESCRIPTION
**Pull request by ramunasd**
Can we release version 2.10.1 ?

### CODE REVIEW

**Comment by lukebakken** [comment]
I'll check out the 2.10.1 milestone and hopefully I can release it today. Thanks for all of your work!

**Comment by lukebakken** [comment]
2.10.1 tagged and packagist updated. I'll announce on `rabbitmq-users`

**Comment by younessadmi** [comment]
Hello,

Why [this commit](https://github.com/php-amqplib/php-amqplib/commit/68bf391ed8427dd4f5e4421781359eb4cbdbd901) is not part of the release ? 😭 

I need this commit because I'm facing an issue regarding a timeout and the following code make sense 
```
...
while ($this->wait_tune_ok) {
    $this->wait(array(
        $this->waitHelper->get_wait('connection.secure'),
        $this->waitHelper->get_wait('connection.tune')
    ), false, $this->connection_timeout);
}
...
```

**Comment by lukebakken** [comment]
@younessadmi commit 68bf391ed8427dd4f5e4421781359eb4cbdbd901 is part of the [`2.11.0`](https://github.com/php-amqplib/php-amqplib/milestone/12) release, which is upcoming. Please be patient.

**Comment by lukebakken** [comment]
@younessadmi if you want to help, please test the code from the `master` branch, which will be version `2.11.0`. Or, please watch the [`rabbitmq-users`]() mailing list where I will announce betas / RCs builds for `2.11.0`. If you can test those it would be very helpful.

**Pull request merged**
