### PR TITLE
Add some constant to AMQP exchange

### PR DESCRIPTION
**Pull request by dream-mo**
When we need rabbitmq exchange type, use constant replace string,such as "direct", "fanout" and so on. You can find it in class PhpAmqpLib\Exchange\AMQPExchange.

### CODE REVIEW

**Comment by ramunasd** [comment]
In addition I would name that class as `final class AMQPExchangeType {}`  and i would strip redundant prefix from all constant names, so instead of `AMQPExhange::AMQP_EX_TYPE_DIRECT` i would prefer `AMQPExchangeType::DIRECT`.

**Comment by dream-mo** [comment]
> In addition I would name that class as `final class AMQPExchangeType {}` and i would strip redundant prefix from all constant names, so instead of `AMQPExhange::AMQP_EX_TYPE_DIRECT` i would prefer `AMQPExchangeType::DIRECT`.

that great

**Comment by ramunasd** [comment]
BTW, amqp extension provides same constants too.
https://github.com/pdezwart/php-amqp/blob/1205d3287df0a9ec762a6594b4fa018ed9637d21/amqp.c#L168

**Comment by dream-mo** [comment]
> 谢谢你的拉动请求。你可以修改代码[`demo`](https://github.com/php-amqplib/php-amqplib/tree/master/demo)来使用这些常量吗？

Ok.I will push a new pull requests

**Pull request merged**
