### PR TITLE
Adapt to recent PHPUnit

### PR DESCRIPTION
**Pull request by DavidPrevot**
This change allows the tests to pass on PHPUnit 7.

### CODE REVIEW

**Comment by ramunasd** [comment]
Hi @DavidPrevot , we dropped support for PHP <5.6 and this fix can be merged. Can You rebase this branch with changes in tests only? Please leave composer.json as it is. Thanks

**Comment by DavidPrevot** [comment]
Updated the request on top of master, tested with PHPUnit 7.5.6 and 8.2.4.

Regards

David

**Comment by ramunasd** [comment]
Thanks a lot. I see tests are failing due to return typehints, which are not supported in PHP5.6
Probably we will increases minimum required version in next minor/major releases, but now it is still PHP5.6

**Comment by DavidPrevot** [comment]
These are the changes needed to actually run PHPUnit 7, I’ll move those needed for PHPUnit 8 in another PR.

Regards

**Comment by lukebakken** [comment]
I have included these changes in #722, thank you.

**Pull request closed without merging**
