### PR TITLE
Catch a couple exceptions in select

### LINKED ISSUE #627: Connection remains  isConnected === true while  AMQPHeartbeatMissedException is thrown
php-amqplib version: 2.8.1

I noticed that AbstractConnection::is_connected remains  equal to "true" while we have an exception 
 AMQPHeartbeatMissedException("Missed server heartbeat") which is thrown from AbstractIO::check_heartbeat()

This happens because neither AMQPHeartbeatMissedException and AMQPRuntimeException are never catched during AbstractIO::read operation;

And as a result we can have a FATAL error inside __destruct because we try to close connection there (AbstractConnection::close()) but got exception  "Broken pipe or closed connection". Or it could have any other bad consequences 

Best Regards

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #627

@programmer512 please review and test if you have time, thanks.

@ramunasd - if you have a second to read #627 and review, I would appreciate it.

### CODE REVIEW

**Comment by ramunasd** [comment]
Hi @lukebakken , thanks for fix. I thought this is fixed after #653. But looks like AbstractConnection->select() is yet another place where things can go wrong.
I suggest to extend AMQPHeartbeatMissedException from AMQPConnectionClosedException ( missed heartbeat is subset of all closed connection issues) and catch AMQPConnectionClosedException here:
 https://github.com/php-amqplib/php-amqplib/blob/3e1a2eb1da6cc2741d109ad6c235df9c9c236c70/PhpAmqpLib/Connection/AbstractConnection.php#L314

Then we will keep consistent exception handling in all places. Agree?

**Comment by lukebakken** [comment]
@ramunasd thank you for the suggestion. This is the last item for `2.9.0` :tada: ... if you have a second for a final review, that would be great. Thanks!

**Comment by ramunasd** [comment]
LGTM, tested it additionaly using testsuites from php-enqueue.

**Comment by lukebakken** [comment]
Thanks!

**Comment by programmer512** [comment]
@lukebakken  thank you for fix.
But my problem was inside check_heartbeat() function which is called from StreamIO::read() method, not from AbstractIO::select(), and this exception "AMQPHeartbeatMissedException" is thrown from there

public function read($len)
{
$this->check_heartbeat();

**Comment by lukebakken** [comment]
This should be caught in `AbstractConnection` now that `AMQPHeartbeatMissedException` derives from `AMQPConnectionClosedException`. There are only three places where `read` is called on an `AMQPReader` instance and `AMQPConnectionClosedException` is handled.

@ramunasd @programmer512 if this could be verified that would be great.

**Comment by programmer512** [comment]
@lukebakken, thank you.
I will prepare a test and verify it.

**Comment by programmer512** [comment]
@ramunasd  , @lukebakken  thank you very much
You are completely right. I did not notice that inside AbstractConnection::wait_frame there is a catch for AMQPConnectionClosedException. So no problem then. Everything is clear and correct from my side.
Sorry for disturbing you because of misunderstanding

**Comment by lukebakken** [comment]
I appreciate that you verified this @programmer512 !!!!

**Pull request merged**
