### PR TITLE
Make sure, that a select interruped by a signal is retried

### PR DESCRIPTION
**Pull request by mruell**
Fixes https://github.com/php-amqplib/php-amqplib/issues/1094 and https://github.com/php-amqplib/php-amqplib/issues/1118

### CODE REVIEW

**Comment by mruell** [comment]
Alright, I think the PR is now in a merge ready state
Happy to get some feedback :)

**Comment by ramunasd** [comment]
Thanks for Your attempt to fix it. Very likelly we will use another approach. The main problem is in misleading AbstractIO::select() result and wrong exception, not the fact it was interrupted.

**Comment by intxcc** [comment]
Hmm - so it is supposed to be interrupted?

**Comment by mruell** [comment]
Thanks for the constructive feedback!
I changed the PR to instead throw the new Exception `AMQPIOWaitInterruptedException`

Hope that helps :)

Best,
Marvin

**Comment by mruell** [comment]
Just noticed what you mean - the error_handler does already catch the interrupt, but does ignore it
So the signal catcher is not needed

Thus I'll close this PR
At least learned a lot about the amqplib ^^

If you want I can create a PR for throwing the correct error within the error_handler

**Pull request closed without merging**
