### PR TITLE
Add work-around to fix 462

### PR DESCRIPTION
**Pull request by fsalehpour**
Adds the necessary code to check if the script is being run under HHVM and set the timeout parameters accordingly before calling stream_select

### CODE REVIEW

**Comment by hairyhum** [comment]
For the `stream_select` function `0` and `null` are different things. `0` means "no wait", while `null` means "wait indefinitely".
According to [HHVM code](https://github.com/facebook/hhvm/blob/222ae58713f5ff44aba46206caf7a021c51b81be/hphp/runtime/ext/sockets/ext_sockets.cpp#L975) `$sec` parameter can be `null`, while `$usec` should be an integer. @fsalehpour can you please update the branch to only convert `$usec` to integer?

**Comment by fsalehpour** [comment]
@hairyhum Thanks and done.

I don't run HHVM myself. So please let me know if it needs any more updates.

**Comment by michaelklishin** [comment]
@fsalehpour thank you. According to GitHub this branch now has conflicts with master. Can you please rebase?

**Comment by fsalehpour** [comment]
@michaelklishin done. :smile:

**Pull request merged**
