### PR TITLE
Allow choosing a different protocol for SSL/TLS

### LINKED ISSUE #641: [2.7,2.8] StreamIO force protocol "ssl" (hardcoded)
Hi,

For some reason (system update or ...) our Php RabbitMQ consumers stopped to work. While searching a solution I've found that forcing [`StreamIO::protocol`](https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Wire/IO/StreamIO.php#L117) value to "tls" in place on "ssl" make all consumers work again.

But this change is not a option, it's a hardcoded value.

Here the piece of code in [`StreamIO::protocol`](https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Wire/IO/StreamIO.php#L117) constructor :
```
        if (is_null($this->context)) {
            // tcp_nodelay was added in 7.1.0
            // ...
        } else {
            $this->protocol = 'ssl';
        }
```

Php version: PHP 7.1.26
Php ssl configuration :
```
$ php -i|grep ssl
Registered Stream Socket Transports => tcp, udp, unix, udg, ssl, tls, tlsv1.0, tlsv1.1, tlsv1.2
openssl
Openssl default config => /usr/lib/ssl/openssl.cnf
openssl.cafile => no value => no value
openssl.capath => no value => no value
```

### PR DESCRIPTION
**Pull request by lukebakken**
Fixes #641

Allows using tls, tlsv1.0, etc as an argument to AMQPSSLConnection ctor

@Cyrille37 please test this branch in your environment.

### CODE REVIEW

**Comment by ramunasd** [comment]
I'm not a fan of long argument list in constructors but this looks fine to me.

**Comment by lukebakken** [comment]
Yeah neither am I but the change has to be backwards compatible. Thank you for reviewing.

**Comment by Cyrille37** [comment]
Thanks for that change.
Do you have a idea of a release with change merged ?

**Comment by lukebakken** [comment]
@Cyrille37 this will be included in version `2.9.0`

**Comment by Cyrille37** [comment]
Thanks a lot !

**Pull request merged**
