### PR TITLE
rm ext-bcmath dependency

### PR DESCRIPTION
**Pull request by terrafrost**
See #694

### CODE REVIEW

**Comment by ramunasd** [comment]
Should we not add bcmath extension as suggested package with explaination why it is needed?

**Comment by ramunasd** [comment]
@terrafrost This one looks like an easy way to get rid of bcmatch extension. But the main problem is not extension itself. It is complicated and messy way in AMQPReader/AMQPWriter how to deal with big integers in 32/64 bit systems.
Take a look at \PhpAmqpLib\Wire\AMQPReader::read_longlong()
Could we use phpseclib directly here without all those checks and workarounds? It would be really nice improvement in terms of performance and simplicity.

**Comment by terrafrost** [comment]
> Take a look at \PhpAmqpLib\Wire\AMQPReader::read_longlong()
Could we use phpseclib directly here without all those checks and workarounds? It would be really nice improvement in terms of performance and simplicity.

Reviewing `read_longlong`...  yah - phpseclib\Math\BigInteger could definitely be used, directly, there. phpseclib uses BigInteger with 64-bit precision here:

https://github.com/phpseclib/phpseclib/blob/e2256f42673633e0e5ff1335faf3a3aa059a894f/phpseclib/Crypt/Hash.php#L891

(PHP didn't introduce support for sha512/224 or sha512/256 until PHP 7.1.0 and phpseclib 2.0 works on PHP 5.3+)

That said, I think `read_php_int` and `read_long` could be updated to work better on 32-bit systems:

```php
list(, $res) = unpack('N', "\xFF\xFF\xFF\xFF");
if ($res < 0) {
    $res = 0x80000000 + ($res & 0x7FFFFFFF);
}
```

Altho PHP doesn't always have 64-bit int support it always has support for [binary64](https://en.wikipedia.org/wiki/Double-precision_floating-point_format), which has a significand precision of 53 bits.

I'll try to do a PR as time permits! The three-day weekend is coming to an end lol.

That said, bcmath_compat would still be useful for stuff like this:

https://github.com/php-amqplib/php-amqplib/blob/master/PhpAmqpLib/Wire/AMQPDecimal.php

**Comment by ramunasd** [comment]
Cool, many thanks @terrafrost

**Comment by terrafrost** [comment]
Superseded by #737

**Pull request closed without merging**
