### PR TITLE
Change phpdoc $delivery_tag type to int

### PR DESCRIPTION
**Pull request by autowp**
To fix static analyzers warnings https://github.com/php-amqplib/php-amqplib/issues/835

### CODE REVIEW

**Comment by ramunasd** [comment]
There is more static analyser warnings. Could You fix them as well?

**Comment by autowp** [comment]
What warnings you mean? Other library internal issues or some issues with $delivery_tag?

There is a lot of detected errors but there is not delivert_tag related findings
```
ERROR: InvalidReturnType - PhpAmqpLib/Channel/AMQPChannel.php:337:16 - The declared return type 'string' for PhpAmqpLib\Channel\AMQPChannel::access_request_ok is incorrect, got 'int' (see https://psalm.dev/011)
     * @return string


ERROR: InvalidReturnStatement - PhpAmqpLib/Channel/AMQPChannel.php:343:16 - The inferred type 'int' does not match the declared return type 'string' for PhpAmqpLib\Channel\AMQPChannel::access_request_ok (see https://psalm.dev/128)
        return $this->default_ticket;


ERROR: InvalidReturnType - PhpAmqpLib/Channel/AMQPChannel.php:683:16 - The declared return type 'array<array-key, string>' for PhpAmqpLib\Channel\AMQPChannel::queue_declare_ok is incorrect, got 'array{string, int|string, int|string}' (see https://psalm.dev/011)
     * @return string[]


ERROR: InvalidReturnStatement - PhpAmqpLib/Channel/AMQPChannel.php:691:16 - The inferred type 'array{string, int|string, int|string}' does not match the declared return type 'array<array-key, string>' for PhpAmqpLib\Channel\AMQPChannel::queue_declare_ok (see https://psalm.dev/128)
        return array($queue, $message_count, $consumer_count);


ERROR: InvalidReturnType - PhpAmqpLib/Channel/AMQPChannel.php:732:16 - The declared return type 'string' for PhpAmqpLib\Channel\AMQPChannel::queue_delete_ok is incorrect, got 'int|string' (see https://psalm.dev/011)
     * @return string


ERROR: InvalidReturnStatement - PhpAmqpLib/Channel/AMQPChannel.php:736:16 - The inferred type 'int|string' does not match the declared return type 'string' for PhpAmqpLib\Channel\AMQPChannel::queue_delete_ok (see https://psalm.dev/128)
        return $reader->read_long();


ERROR: InvalidReturnType - PhpAmqpLib/Channel/AMQPChannel.php:768:16 - The declared return type 'string' for PhpAmqpLib\Channel\AMQPChannel::queue_purge_ok is incorrect, got 'int|string' (see https://psalm.dev/011)
     * @return string


ERROR: InvalidReturnStatement - PhpAmqpLib/Channel/AMQPChannel.php:772:16 - The inferred type 'int|string' does not match the declared return type 'string' for PhpAmqpLib\Channel\AMQPChannel::queue_purge_ok (see https://psalm.dev/128)
        return $reader->read_long();


ERROR: InvalidArgument - PhpAmqpLib/Channel/AMQPChannel.php:863:23 - The second param of the closure passed to array_reduce must take array-key but only accepts string (see https://psalm.dev/004)
             * @param string $key


ERROR: InvalidPropertyAssignmentValue - PhpAmqpLib/Channel/AMQPChannel.php:1006:9 - $this->callbacks with declared type 'array<array-key, callable>' cannot be assigned type 'non-empty-array<array-key, callable|null>' (see https://psalm.dev/145)
        $this->callbacks[$consumer_tag] = $callback;


ERROR: InvalidReturnType - PhpAmqpLib/Channel/AbstractChannel.php:141:16 - The declared return type 'string' for PhpAmqpLib\Channel\AbstractChannel::getChannelId is incorrect, got 'int' (see https://psalm.dev/011)
     * @return string


ERROR: InvalidReturnStatement - PhpAmqpLib/Channel/AbstractChannel.php:145:16 - The inferred type 'int' does not match the declared return type 'string' for PhpAmqpLib\Channel\AbstractChannel::getChannelId (see https://psalm.dev/128)
        return $this->channel_id;


ERROR: InvalidNullableReturnType - PhpAmqpLib/Channel/AbstractChannel.php:164:16 - The declared return type 'PhpAmqpLib\Connection\AbstractConnection' for PhpAmqpLib\Channel\AbstractChannel::getConnection is not nullable, but 'PhpAmqpLib\Connection\AbstractConnection|null' contains null (see https://psalm.dev/144)
     * @return AbstractConnection


ERROR: NullableReturnStatement - PhpAmqpLib/Channel/AbstractChannel.php:168:16 - The declared return type 'PhpAmqpLib\Connection\AbstractConnection' for PhpAmqpLib\Channel\AbstractChannel::getConnection is not nullable, but the function returns 'PhpAmqpLib\Connection\AbstractConnection|null' (see https://psalm.dev/139)
        return $this->connection;


ERROR: InvalidArgument - PhpAmqpLib/Connection/AMQPSSLConnection.php:35:13 - Argument 8 of PhpAmqpLib\Connection\AMQPStreamConnection::__construct expects null, mixed|null provided (see https://psalm.dev/004)
            isset($options['login_response']) ? $options['login_response'] : null,


ERROR: InvalidArgument - PhpAmqpLib/Connection/AMQPSSLConnection.php:39:13 - Argument 12 of PhpAmqpLib\Connection\AMQPStreamConnection::__construct expects null, null|resource provided (see https://psalm.dev/004)
            $ssl_context,


ERROR: InvalidArgument - PhpAmqpLib/Connection/AMQPSocketConnection.php:86:27 - Argument 8 of PhpAmqpLib\Connection\AMQPSocketConnection::__construct expects null, mixed|null provided (see https://psalm.dev/004)
                          $login_response,


ERROR: InvalidArgument - PhpAmqpLib/Connection/AMQPStreamConnection.php:103:27 - Argument 8 of PhpAmqpLib\Connection\AMQPStreamConnection::__construct expects null, mixed|null provided (see https://psalm.dev/004)
                          $login_response,


ERROR: InvalidArgument - PhpAmqpLib/Connection/AMQPStreamConnection.php:107:27 - Argument 12 of PhpAmqpLib\Connection\AMQPStreamConnection::__construct expects null, mixed|null provided (see https://psalm.dev/004)
                          $context,


ERROR: InvalidArgument - PhpAmqpLib/Connection/AbstractConnection.php:517:47 - Argument 1 of PhpAmqpLib\Helper\DebugHelper::debug_method_signature1 expects string, array<array-key, mixed> provided (see https://psalm.dev/004)
        $this->debug->debug_method_signature1($method_sig);


ERROR: InvalidArgument - PhpAmqpLib/Connection/AbstractConnection.php:548:47 - Argument 1 of PhpAmqpLib\Helper\DebugHelper::debug_method_signature1 expects string, array<array-key, mixed> provided (see https://psalm.dev/004)
        $this->debug->debug_method_signature1($method_sig);


ERROR: InvalidNullableReturnType - PhpAmqpLib/Connection/AbstractConnection.php:623:16 - The declared return type 'array<array-key, mixed>' for PhpAmqpLib\Connection\AbstractConnection::wait_channel is not nullable, but 'array{mixed, mixed}|null' contains null (see https://psalm.dev/144)
     * @return array


ERROR: UndefinedMethod - PhpAmqpLib/Connection/AbstractConnection.php:1131:25 - Method PhpAmqpLib\Connection\AbstractConnection::try_create_connection does not exist (see https://psalm.dev/022)
                $conn = static::try_create_connection($host, $port, $user, $password, $vhost, $options);


ERROR: LoopInvalidation - PhpAmqpLib/Helper/MiscHelper.php:92:17 - Variable $j has already been assigned in a for/foreach loop (see https://psalm.dev/130)
                $j = 0;


ERROR: UndefinedMethod - PhpAmqpLib/Wire/AMQPReader.php:423:65 - Method PhpAmqpLib\Wire\AMQPTable::offsetSet does not exist (see https://psalm.dev/022)
            $returnObject ? $result->set($name, $val, $ftype) : $result[$name] = array($ftypeSym, $val);


ERROR: InvalidArgument - PhpAmqpLib/Wire/AMQPReader.php:457:56 - Argument 2 of PhpAmqpLib\Wire\AMQPArray::push expects null, int provided (see https://psalm.dev/004)
            $returnObject ? $result->push($fieldValue, $fieldType) : $result[] = $fieldValue;


ERROR: UndefinedMethod - PhpAmqpLib/Wire/AMQPReader.php:457:70 - Method PhpAmqpLib\Wire\AMQPArray::offsetSet does not exist (see https://psalm.dev/022)
            $returnObject ? $result->push($fieldValue, $fieldType) : $result[] = $fieldValue;


ERROR: InvalidReturnType - PhpAmqpLib/Wire/IO/AbstractIO.php:77:16 - The declared return type 'int' for PhpAmqpLib\Wire\IO\AbstractIO::select is incorrect, got 'int|true' (see https://psalm.dev/011)
     * @return int


ERROR: InvalidReturnStatement - PhpAmqpLib/Wire/IO/AbstractIO.php:101:16 - The inferred type 'int|true' does not match the declared return type 'int' for PhpAmqpLib\Wire\IO\AbstractIO::select (see https://psalm.dev/128)
        return $result;


ERROR: InvalidArgument - PhpAmqpLib/Wire/IO/AbstractIO.php:206:27 - Argument 1 of set_error_handler expects callable(int, string, string=, int=, array<array-key, mixed>=):bool|null, array{PhpAmqpLib\Wire\IO\AbstractIO&static, string(error_handler)} provided (see https://psalm.dev/004)
        set_error_handler(array($this, 'error_handler'));


ERROR: InvalidNullableReturnType - PhpAmqpLib/Wire/IO/SocketIO.php:89:21 - The declared return type 'resource' for PhpAmqpLib\Wire\IO\SocketIO::getSocket is not nullable, but 'null|resource' contains null (see https://psalm.dev/144)
    public function getSocket()


ERROR: NullableReturnStatement - PhpAmqpLib/Wire/IO/SocketIO.php:91:16 - The declared return type 'resource' for PhpAmqpLib\Wire\IO\SocketIO::getSocket is not nullable, but the function returns 'null|resource' (see https://psalm.dev/139)
        return $this->sock;


ERROR: InvalidArgument - PhpAmqpLib/Wire/IO/SocketIO.php:241:30 - Argument 1 of socket_select expects array<array-key, resource>|null, array{null|resource} provided (see https://psalm.dev/004)
        return socket_select($read, $write, $except, $sec, $usec);


ERROR: InvalidArgument - PhpAmqpLib/Wire/IO/SocketIO.php:252:37 - Argument 2 of socket_select expects array<array-key, resource>|null, array{null|resource} provided (see https://psalm.dev/004)
        return socket_select($read, $write, $except, 0, 100000);


ERROR: InvalidPropertyAssignmentValue - PhpAmqpLib/Wire/IO/StreamIO.php:317:20 - $this->sock with declared type 'null|resource' cannot be assigned type 'closed-resource' (see https://psalm.dev/145)
            fclose($this->sock);


ERROR: InvalidNullableReturnType - PhpAmqpLib/Wire/IO/StreamIO.php:327:21 - The declared return type 'resource' for PhpAmqpLib\Wire\IO\StreamIO::getSocket is not nullable, but 'null|resource' contains null (see https://psalm.dev/144)
    public function getSocket()


ERROR: NullableReturnStatement - PhpAmqpLib/Wire/IO/StreamIO.php:329:16 - The declared return type 'resource' for PhpAmqpLib\Wire\IO\StreamIO::getSocket is not nullable, but the function returns 'null|resource' (see https://psalm.dev/139)
        return $this->sock;


ERROR: InvalidArgument - PhpAmqpLib/Wire/IO/StreamIO.php:341:30 - Argument 1 of stream_select expects array<array-key, resource>, array{null|resource} provided (see https://psalm.dev/004)
        return stream_select($read, $write, $except, $sec, $usec);


ERROR: NullArgument - PhpAmqpLib/Wire/IO/StreamIO.php:352:30 - Argument 1 of stream_select cannot be null, null value provided to parameter with type array<array-key, resource> (see https://psalm.dev/057)
        return stream_select($read, $write, $except, 0, 100000);


ERROR: InvalidArgument - PhpAmqpLib/Wire/IO/StreamIO.php:352:37 - Argument 2 of stream_select expects array<array-key, resource>|null, array{null|resource} provided (see https://psalm.dev/004)
        return stream_select($read, $write, $except, 0, 100000);


------------------------------
40 errors found
------------------------------
425 other issues found.
```

**Comment by autowp** [comment]
Hm... i found comment:

```
Even on 64 bit systems PHP integers are signed.
Since we need an unsigned value here we return it as a string.
```

Maybe my pull request is invalid due that. Right solution is `string|int $delivery_tag` everywhere

**Comment by ramunasd** [comment]
It's impossible to reach non integer `$delivery_tag` value even on 32bit systems, it's a 2^31-1

**Comment by andrew-demb** [comment]
Hello @ramunasd .
I discovered in rabbitmq docs mention, that delivery tag have type `longlong` ([64-bit integer])
https://www.rabbitmq.com/amqp-0-9-1-reference.html#domain.delivery-tag

My knowledge in Erlang is limited, but also I find in rabbitmq server source code generation next delivery tag by simply increment by 1
https://github.com/rabbitmq/rabbitmq-server/blob/b460ea1b4f41c5547f03c316e758be61bdcd0f2e/src/rabbit_channel.erl#L1963

Maybe the delivery tag may be bigger, than 2^31-1?

**Pull request merged**
