### PR TITLE
Add Contributor Code of Conduct

### PR DESCRIPTION
**Pull request by postalservice14**
Thoughts or concerns about adding this CoC to the project?  Please avoid the "drama"...  :-)

### CODE REVIEW

**Comment by videlalvaro** [comment]
What's the suggested way of reporting violations? It has to be private.

**Comment by postalservice14** [comment]
Yeah, I wasn't sure how to handle that... :-/  Any ideas?  I didn't want to put just my email address, that didn't seem right...

**Comment by videlalvaro** [comment]
Yeah. Let's ask github support to add a "report" button of sorts. If we all three ask they might pay attention

**Comment by nubeiro** [comment]
I agree, violation reports must be private, so that we can try to solve issues between implied parties.

**Comment by nubeiro** [comment]
If requesting a report button does not work, we might try to use what @postalservice14 suggested, which is letting the reporter try to find out how to contact us... our e-mail addresses are in composer.json file. If that is not enough, we could consider adding Twitter accounts in readme file or even mentioning we use Gitter as IM tool.

**Comment by postalservice14** [comment]
I sent a support request to Github as well....

For the time being, do we want to leave it as is?

**Comment by nubeiro** [comment]
I got reply today that they would " pass your suggestion to the team to consider" but no promises made on actually getting something done. 
I'd leave it as it is, if we ever get a "private report" button then we can update CoC

**Comment by postalservice14** [comment]
Sounds good to me.

**Comment by videlalvaro** [comment]
I've got the same reply from them

**Pull request merged**
