### PR TITLE
add message delivery tag for internal ack handler

### PR DESCRIPTION
**Pull request by prolic**

### CODE REVIEW

**Comment by prolic** [comment]
ping @postalservice14 @nubeiro

**Comment by prolic** [comment]
ping @michaelklishin

**Comment by prolic** [comment]
hello??? any feedback on this?

**Comment by hairyhum** [comment]
@prolic can you please provide more context for this PR? And also some tests that will verify that this change is necessary?

**Comment by michaelklishin** [comment]
This seems to try to attach a delivery tag sent by RabbitMQ (on a channel w/ enabled publisher confirms). I'm afraid this is confusing as delivery tags on messages are typically only set for deliveries.

Please clarify what the goal here and we'll consider re-opening this but at first glance this looks like something I wouldn't accept in any client libraries I maintain.

**Comment by prolic** [comment]
@michaelklishin I was working on an unit test for this, until I get notice you closed it already.

I use this for publisher confirms, correct.

The reason is, that if the delivery tag is missing (which is set by RabbitMQ), I cannot use this information in the nack handler.

It would also be consistent behaviour with php-amqp extension, see here: https://github.com/pdezwart/php-amqp/blob/master/stubs/AMQPChannel.php#L197-L216

Having the delivery tag available, allows to give specific nack handlers to tell message with delivery tag XY has been rejected, instead of only referring to the message  body (which could be the same for different messages).

**Comment by prolic** [comment]
@michaelklishin any comments on my last comment?

**Comment by michaelklishin** [comment]
@prolic I get notifications for the repository, no need to ping me personally every time.

**Comment by prolic** [comment]
sure, will do

**Comment by prolic** [comment]
added tests!

**Comment by michaelklishin** [comment]
The tests don't seem to pass on PHP 5.3 through 5.5. I restarted the build to be more certain that it's not a timing issue in the test suite.

**Comment by prolic** [comment]
Ok. Will check again later.

**Comment by prolic** [comment]
ok should be good now, sorry for abusing travis for this, but I don't have any EOL php versions on my system any more :-)

**Comment by michaelklishin** [comment]
@prolic thank you!

**Comment by prolic** [comment]
When can I expect a new release?

**Comment by michaelklishin** [comment]
@prolic see #469.

**Pull request merged**
