### PR TITLE
Fixed AMQPProtocolException phpdoc arguments type annotations

### PR DESCRIPTION
**Pull request by zerkms**
Fixes https://github.com/php-amqplib/php-amqplib/issues/844

### CODE REVIEW

**Comment by ramunasd** [comment]
Thanks for doc improvement. Could You fix other doc blocks as well?

**Comment by zerkms** [comment]
I only happened to find this one (because I needed to create an instance of `AMQPProtocolException` exception).

I will have a look into it on monday then.

**Comment by zerkms** [comment]
It looks like only `AMQPException` is also affected?

**Comment by zerkms** [comment]
I checked the other class (`AMQPException`) as well.

Ideally this (and basically every other) project needs to have psalm to ensure it does not happen.

**Pull request merged**
