### PR TITLE
StreamIO: delay context init upon connect

### LINKED ISSUE #1152: Lazy stream connection leaks stream context resource causing file descriptor limit hit (FD_SETSIZE)
**Version(s) affected**: 
- 3.6.0

**Description**  
We are facing file descriptor limit hit in our CI causing failure in stream_select. This [has been reported multiple times](https://github.com/php-amqplib/php-amqplib/issues?q=is%3Aissue+is%3Aclosed+FD_SETSIZE). We found that the leaking descriptor is the stream-context used in [StreamIO::$context](https://github.com/php-amqplib/php-amqplib/blob/abee57c/PhpAmqpLib/Wire/IO/StreamIO.php#L16) when lazy connection is used. The context is created in constructor no matter if connection was lazy or not. And closing the connection does not help as `connection->close()` does not clear this context in such case.

The error is:
```
stream_select(): You MUST recompile PHP with a larger value of FD_SETSIZE.
It is set to 1024, but you have descriptors numbered at least as high as 1029.
 --enable-fd-setsize=2048 is recommended, but you may want to set it
to equal the maximum number of open files supported by your system,
in order to avoid seeing this error again at a later date.
```

**How to reproduce**  

Fully reproduced in following PR:
- #1150

**Possible Solution**  

Fixed in following PR:
- #1151

### PR DESCRIPTION
**Pull request by janedbal**
Resolves #1152

### CODE REVIEW

**Review by ramunasd — CHANGES_REQUESTED** [review]
Good catch. I think private property `$context` must be cleared on disconnect. That would completely solve FD leak.

**Comment by ramunasd** [comment]
Or better, do not keep created `$context`. Method `setupContext()` can return created/altered `$context` to method `connect()`.

**Comment by janedbal** [comment]
Turns out, this was not the root cause of our FD issue...

**Comment by ramunasd** [comment]
Closed in favour of #1154

**Pull request closed without merging**
