### PR TITLE
PHP 8 support

### PR DESCRIPTION
**Pull request by patrickkusebauch**
Resolves: https://github.com/php-amqplib/php-amqplib/issues/903

I just made changes to reflect how the other version of the Protocol looks like.

### CODE REVIEW

**Comment by lukebakken** [comment]
Please see #858

**Comment by ramunasd** [comment]
@lukebakken this PR is also related PHP8, looks like missing yet neccessary fix

**Comment by lukebakken** [comment]
Thank you @patrickkusebauch and thanks @ramunasd for noticing.

**Comment by lukebakken** [comment]
`v3.0.0-rc2` released - https://packagist.org/packages/php-amqplib/php-amqplib#v3.0.0-rc2

**Pull request merged**
