### PR TITLE
fix for issues #415 and #261 - using empty($this->...) instead of ! $this

### PR DESCRIPTION
**Pull request by andreyrevinate**
on object properties.

### CODE REVIEW

**Comment by zerkms** [comment]
5 cents from me: there is no *evidence* this solution covers my report #415

**Comment by claudusd** [comment]
Hi,

I have a segmentation fault problem with the last version (v2.6.3).
I try to use this branch to check if my segfault it's still here.
This branch fix my problem.

**Comment by tiborb** [comment]
Hi, @postalservice14 could you merge this fix? It is a major bug as well in our env.

**Comment by michaelklishin** [comment]
This change looks straightforward and pretty safe => I'll take the liberty of merging it.

**Comment by michaelklishin** [comment]
@zerkms perhaps you can check if master works better for you now?

**Comment by zerkms** [comment]
@michaelklishin this PR does not fix the issue with garbage-collecting the connection object prematurely. 

I honestly fail to understand how replacing `!` with `!empty` check for `null` vs `object` values changes anything.
Could someone please explain why this PR works? And what exact problem it fixes?

From the comments it looked that people came with random problems and the random problems disappeared. But if someone cannot reliably reproduce a problem I'm not sure how one knows the fix fixed it, not just shifted somewhere else.

**Comment by nemenemsrouge** [comment]
Hello,

https://github.com/php-amqplib/php-amqplib/issues/415#issuecomment-238857545

A related ticket with an alternative temporary solution.

It works for us

**Comment by mledoze** [comment]
@zerkms you are absolutely right, I too do not understand why the proposed changes fix the segmentation faults.
For some reasons I am stuck with the version 2.6.3 which is shipped with Debian 9 and I managed to fix the segmentation faults with the workaround proposed by @UlrichKu here : https://github.com/php-amqplib/php-amqplib/issues/415#issuecomment-238857545

**Pull request merged**
