### PR TITLE
Lazy socket connection

### LINKED ISSUE #331: Lazy connections and `AMQPSocketConnection`
Hey guys,

From what I've noticed (according to benchmarks at least) using `AMQPSocketConnection` for producers 10x faster than stream implementation:

```
$ make benchmark
Publishing 4000 msgs with 1KB of content:
php benchmark/producer.php 4000
0.65707993507385
Consuming 4000:
php benchmark/consumer.php
Pid: 26125, Count: 4000, Time: 4.1040
Stream produce 100:
php benchmark/stream_tmp_produce.php 100
4.5005960464478
Socket produce 100:
php benchmark/socket_tmp_produce.php 100
0.53135895729065
```

I would like to test socket connection on our system but it lacks lazy connection in current implementation. Are there any reasons why `AMQPSocketConnection` class still doesn't support lazy connection? Except nobody actually implemented it :). Willing to help if that's the case.

### PR DESCRIPTION
**Pull request by mente**
Speaking of #331 . I wanted to have a generic lazy connection class that wraps real connection. But current class structure so flawed so I ended up with this simple solution.

Closes #331

### CODE REVIEW

**Comment by mente** [comment]
Can I ignore the problem from Scrutinizer? From what I see it's missing code coverage and I have no clue how to add it

**Comment by postalservice14** [comment]
Looks like the Travis build took longer than normal for some reason, so scrutinizer timed out waiting for the coverage results from Travis.  @videlalvaro could rerun the travis build and scrutinizer, or could just ignore it since the build passed.

**Comment by mente** [comment]
From what I see there all recent PRs have failed due to same reason. There's one test that takes a lot of time. I would try to find it

**Comment by mente** [comment]
```
Starting test 'PhpAmqpLib\Tests\Unit\WireTest::testShortWriteRead'.
.
Starting test 'PhpAmqpLib\Tests\Unit\WireTest::testShortOutOfRangeLower'.
.
Starting test 'PhpAmqpLib\Tests\Unit\WireTest::testShortOutOfRangeUpper'.
.
Starting test 'PhpAmqpLib\Tests\Unit\WireTest::testSignedShortWriteRead'.
.
Starting test 'PhpAmqpLib\Tests\Unit\WireTest::testSignedShortOutOfRangeLower'.
.
Starting test 'PhpAmqpLib\Tests\Unit\WireTest::testSignedShortOutOfRangeUpper'.
.
Starting test 'PhpAmqpLib\Tests\Unit\WireTest::testLongWriteRead'.
.
Starting test 'PhpAmqpLib\Tests\Unit\WireTest::testLongOutOfRangeLower'.
.
Starting test 'PhpAmqpLib\Tests\Unit\WireTest::testLongOutOfRangeUpper'.
.
Starting test 'PhpAmqpLib\Tests\Unit\WireTest::testSignedLongWriteRead'.
.
Starting test 'PhpAmqpLib\Tests\Unit\WireTest::testSignedLongOutOfRangeLower'.
.
Starting test 'PhpAmqpLib\Tests\Unit\WireTest::testSignedLongOutOfRangeUpper'.
.
Starting test 'PhpAmqpLib\Tests\Unit\WireTest::testLonglongWriteRead'.
```

And some more

**Comment by postalservice14** [comment]
This looks good to me.  @nubeiro look good to you?

**Comment by nubeiro** [comment]
Looks good to me, thanks a lot @mente

**Comment by postalservice14** [comment]
@mente Can you rebase off of master to fix the merge conflicts?  Thanks!

**Comment by mente** [comment]
Yes sure

**Comment by mente** [comment]
Here you go

**Pull request merged**
