### PR TITLE
CI workflow updates

### PR DESCRIPTION
**Pull request by lukebakken**
* Start RabbitMQ using `docker run` so a restart is not necessary.
* Use latest `toxiproxy` version

@ramunasd I've copied some scripts from [here](https://github.com/rabbitmq/rabbitmq-dotnet-client/tree/main/.ci/ubuntu) to set up GitHub actions for tests. In another PR, I'll do the same for Windows tests, and remove the AppVeyor build.

### CODE REVIEW

**Comment by ramunasd** [comment]
why?

**Comment by lukebakken** [comment]
It removes the RabbitMQ restart, also, the script I added can be run locally to get a test environment going. I can add that to the docs.

**Comment by ramunasd** [comment]
local test environment was working fine 🤷

**Comment by lukebakken** [comment]
@ramunasd I'm going to add instructions for running a local test environment.

How do you do it? I'm assuming using `docker compose up` but I'm a bit mystified by what the `php` service does.

**Comment by ramunasd** [comment]
Well yes, `docker-compose` deos the job. That script You wrote basically is overengineered version of docker-compose :)
php container has php itself and can run tests.

**Comment by lukebakken** [comment]
> You wrote basically is overengineered version of docker-compose :)

Ha, yes, but it does work well for GitHub actions.

> php container has php itself and can run tests

Yep, but ... how? I just ran `docker compose up` and then `docker compose exec php /bin/bash`. When I run `./vendor/bin/phpunit` I received an error that PhP 7.1 was unsupported, and that 7.3 was required.

So, I updated `docker/php/Dockerfile` to use `7-php`. Working on this further, and I will document it as well.

**Comment by lukebakken** [comment]
Using `7-php` in `docker/php/Dockerfile` does not work for running tests, as there are missing functions. Giving `8-php` a try now.

**Comment by lukebakken** [comment]
OK great, down to two errors:

```
There were 2 errors:

1) PhpAmqpLib\Tests\Unit\Wire\IO\SocketIOTest::connect_ipv6
PhpAmqpLib\Exception\AMQPIOException: Error Connecting to server (111): Connection refused

/src/PhpAmqpLib/Wire/IO/SocketIO.php:82
/src/tests/Unit/Wire/IO/SocketIOTest.php:33

2) PhpAmqpLib\Tests\Unit\Wire\IO\StreamIOTest::connect_ipv6
PhpAmqpLib\Exception\AMQPIOException: stream_socket_client(): Unable to connect to tcp://[::1]:5672 (Connection refused)

/src/PhpAmqpLib/Wire/IO/StreamIO.php:95
/src/tests/Unit/Wire/IO/StreamIOTest.php:59
```

I'll commit my latest changes.

**Comment by ramunasd** [comment]
docker dev image is based on oldest supported php version, which is 7.2
Very likely your local setup already had compose.lock file built with newer php version, that's why You get an error.
so `docker compose down` and `rm composer.lock` does the trick.
In CI we don't have such issues as workspace is always clean.

**Comment by lukebakken** [comment]
Thank you for the explanation, I'm sure that was the issue. I will document it.

**Comment by lukebakken** [comment]
@ramunasd no hurry, take a look when you have time. Thanks!

**Comment by ramunasd** [comment]
I see Your efforts to make thing better, but this looks overcomplicated. I don't understand why You want to remove php container from docker-compose? It was really fine before, kind of community standard to use docker-compose directly.

If You want have ability to rebuild images, then it can solved with simple `docker-compose build --no-cache` as separate make target :shrug:

If You really want, go ahead, but I wont use it :)

**Comment by lukebakken** [comment]
> If You really want, go ahead, but I wont use it :)

Noted! The changes in this PR are similar to those I have done in the .NET client and other client libraries that Team RabbitMQ maintains. It'll make it easier for me to remember how to do things like run tests when I switch between client libraries.

**Pull request merged**
