### PR TITLE
Handle exit signals async if possible

### PR DESCRIPTION
**Pull request by igrizzli**
Implement #468

### CODE REVIEW

**Comment by ramunasd** [comment]
Sorry, this does not make sense to me. If You enable async signals in your consumer, then just define `AMQP_WITHOUT_SIGNALS` as `true` and it wont dispatch anything.

**Comment by igrizzli** [comment]
> Sorry, this does not make sense to me. If You enable async signals in your consumer, then just define `AMQP_WITHOUT_SIGNALS` as `true` and it wont dispatch anything.

Removing of this code in 3.x.x milestone, as i understand, this way better than removing, so if it's not let's decline this PR.

**Comment by ramunasd** [comment]
There is no plans to remove `pcntl_signal_dispatch()`. Very likely 3.x.x will support PHP 7.0.

**Comment by igrizzli** [comment]
> There is no plans to remove `pcntl_signal_dispatch()`. Very likely 3.x.x will support PHP 7.0.

it's marked as 3.x.x milestone here:
https://github.com/php-amqplib/php-amqplib/issues/468

**Pull request closed without merging**
