### PR TITLE
Allow external login method

### PR DESCRIPTION
**Pull request by alexanderbirch**
Adds external login method from connection factory through abstract connection.

### CODE REVIEW

**Comment by ramunasd** [comment]
Tests are required. Thank You for contribution.

**Comment by ramunasd** [comment]
@alexanderbirch can You allow edit for maintainers? Here is the link about how to do it:
https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork

Otherwise I will recreate this PR with tests and improvements.
Thanks

**Comment by alexanderbirch** [comment]
> @alexanderbirch can You allow edit for maintainers? Here is the link about how to do it: https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork
> 
> Otherwise I will recreate this PR with tests and improvements. Thanks

It seems the option is already enabled. Let me know if I can do anything more.

**Comment by ramunasd** [comment]
Apparently I cannot push more commits because PR is created from `master` branch. I will recreate..

**Comment by lukebakken** [comment]
@alexanderbirch just so you know - in the future, you should create a branch in your fork to do work on pull requests. This applies to `git` in general, not just PRs on GitHub.

**Comment by ramunasd** [comment]
Recreated as #1064 
Thanks @alexanderbirch

**Pull request closed without merging**
