### PR TITLE
allow assoc array and generator for connection creation

### PR DESCRIPTION
**Pull request by black-silence**
I tried to run unittests but it's impossible on php 7.3

### CODE REVIEW

**Comment by ramunasd** [comment]
Then why travic-ci works well? What is the error?

**Comment by lukebakken** [comment]
As you can see here, php 7.3.5 works just fine:

```
$ php --version
PHP 7.3.5 (cli) (built: Apr 30 2019 21:05:09) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.5, Copyright (c) 1998-2018 Zend Technologies
lbakken@shostakovich ~/development/php-amqplib/php-amqplib (master $=)
$ make test
./vendor/bin/phpunit
PHPUnit 4.8.36 by Sebastian Bergmann and contributors.

Runtime:        PHP 7.3.5
Configuration:  /home/lbakken/development/php-amqplib/php-amqplib/phpunit.xml.dist
Warning:        The Xdebug extension is not loaded
                No code coverage will be generated.

...............................................................  63 / 766 (  8%)
............................................................... 126 / 766 ( 16%)
............................................................... 189 / 766 ( 24%)
............................................................... 252 / 766 ( 32%)
............................................................... 315 / 766 ( 41%)
............................................................... 378 / 766 ( 49%)
............................................................... 441 / 766 ( 57%)
............................................................... 504 / 766 ( 65%)
............................................................... 567 / 766 ( 74%)
............................................................... 630 / 766 ( 82%)
............................................................... 693 / 766 ( 90%)
......................................................SSSSSSSS. 756 / 766 ( 98%)
..........

Time: 6.79 seconds, Memory: 12.00MB

There were 8 skipped tests:

OK, but incomplete, skipped, or risky tests!
Tests: 766, Assertions: 947, Skipped: 8.
```

**Comment by black-silence** [comment]
The error is that the contrib doc says to use ```$ phpunit``` to run tests.

What is the actual reason this is closed without comment?

**Comment by lukebakken** [comment]
> The error is that the contrib doc says to use $ phpunit to run tests

Yes, if you have `phpunit` 4.8.X in your `PATH`, it should work. If you look at the contents of the `Makefile`,  you can see that `make test` runs this command:

```
.PHONY: test
test:
        ./vendor/bin/phpunit
```

> What is the actual reason this is closed without comment?

I see no reason to merge this pull request. Running tests works fine on Travis CI and on my workstation, and there is no information as to why this pull request is necessary.

**Comment by black-silence** [comment]
The contrib file should be fixed to say vendor/bin/phpunit instead of just phpunit. I think it's weird to assume that someone has this stone age version of phpunit in PATH.

This PR removes a pointless limitation in create_connection. You are forcing users to give a plain list of hosts. I can't use a generator or indexed array. 

I didn't think I'd have to waste time by creating an enhancement issue if I could just improve the code.

**Comment by lukebakken** [comment]
> This PR removes a pointless limitation in create_connection. You are forcing users to give a plain list of hosts. I can't use a generator or indexed array

Great. That explanation would have been very helpful in your original comment as your one-line description did not provide that information.

> The contrib file should be fixed to say vendor/bin/phpunit instead of just phpunit.

Please add this change to your pull request, thanks.

Finally, add tests to your pull request demonstrating that your change works as intended, and is backwards-compatible, and I will happily merge it.

**Comment by black-silence** [comment]
I'll try to remember that the commit message is not enough explanation

**Comment by lukebakken** [comment]
I can't merge this PR without tests demonstrating that it both is backwards compatible and supports your requirements.

**Comment by lukebakken** [comment]
Thank you

**Pull request merged**
