### PR TITLE
Add Additional Test Coverage for AMQPConnectionConfig Class

### PR DESCRIPTION
**Pull request by salehhashemi1992**
Introduce new unit tests to improve the test coverage for the AMQPConnectionConfig class. 

The tests validate:
- Invalid port number
- Invalid login method
- Invalid SSL settings
- Invalid AMQP protocol
- Invalid stream context

And also some typo fixes.

### CODE REVIEW

**Comment by ramunasd** [comment]
Thanks for Your fixes. Can You merge all of them to one PR?

**Comment by salehhashemi1992** [comment]
> Thanks for Your fixes. Can You merge all of them to one PR?

You're welcome. Done 👌

**Comment by salehhashemi1992** [comment]
I'll check the ci error

**Comment by salehhashemi1992** [comment]
Is it necessary to have manual approval for the CI run each time a commit is added?

**Comment by lukebakken** [comment]
@salehhashemi1992 that seems like a GitHub thing to me. If you can figure out how we can change it, I'm happy to do so.

**Comment by salehhashemi1992** [comment]
of course. you can go to settings->actions->general->`Fork pull request workflows from outside collaborators`
and change it to the first option `Require approval for first-time contributors who are new to GitHub`
@lukebakken @ramunasd

**Comment by lukebakken** [comment]
@salehhashemi1992 done! Thanks for the instructions on how to change that setting.

**Comment by salehhashemi1992** [comment]
Now it's ready to merge @lukebakken

**Review by ramunasd — APPROVED** [review]

**Review by lukebakken — APPROVED** [review]

**Pull request merged**
